version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "
            pip install Pillow &&
            python manage.py migrate &&
            python manage.py makemigrations &&
            python manage.py test &&
            python manage.py runserver 0.0.0.0:8000"
      
volumes:
  dev-db-data:
  dev-static-data: