# Generated by Django 3.2.25 on 2024-06-19 16:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mange',
            name='profile',
            field=models.ImageField(null=True, upload_to=core.models.mange_image_file_path),
        ),
    ]
