# Generated by Django 3.2.25 on 2024-06-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mange_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mange',
            name='profile',
            field=models.ImageField(upload_to=''),
        ),
    ]
