# Generated by Django 3.2.25 on 2024-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mange_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mange',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='mange_profiles/'),
        ),
    ]
